### ISSUE TITLE
Key size

### ISSUE THREAD

**Issue by padak** [keboola/ssh-keygen#2]
Can we change how big ssh keys are? [Here](https://github.com/keboola/ssh-keygen/blob/master/src/run.php) I can see that we're using RSA 2048. Can we simple change it to 4096? Idea comes from [this](https://blog.g3rt.nl/upgrade-your-ssh-keys.html) article + client's questions related to SSH tunnel security.

P.

**Comment by ErikZigo** [comment]
Zmeneno a nasazeno https://github.com/keboola/ssh-keygen/releases/tag/0.0.4
